sudo: required

language: generic

services:
- docker

before_install:
- pip install --user construi

script:
- construi test

deploy:
  provider: script
  script: construi release
  on:
    tags: true


env:
  global:
    - TWINE_USERNAME=levi.stephen
    - secure: "DEisxLhT/4Fe/ZEaLwVqueNY0MUtGTeyD+NpbX4YQmBsiQQWXPxJAMzv49p2hfBahCxtnW5jGMsIL99YAMfKYdFcLnOMbAGNVP3XVfeGC0h7Ij8iBv/waqpGP8AY1HMHtqddOue51HkJvAM0fIJixkE36zACu1ZzVcWsCVjEY0uP+t9uY/PPyuDbqqoAMRLFQZn5VCSUww6N9dn3E4gP/zV/jrUyIXMxmzzQgJtuTabSEmHT/eB3Ui4c2vh/b/59e032S7s69GzrPRsgKukHjh6baRTi6wYNW7NQE1yDK/iDe+/nfvpV7Tf/t47KxxQE25IXz1Wosz2E51UaMwD87N6wuSisH4OkCw2kLF7X9Z/3lItAuIlLrGIHHB0rwUQsh3cT3fOWOVdU7i06keJszt0hUrnviv2xCrvZFJF0TUqTsOdey1+5/sgVVAdnAyUE9AmbdV49gfEIpNM1MZijKp0lqCaE9no9w4B20bIfXyiP1dM9gUcDt3GMnQ8EUJe9IjyqyG1IQbu8SMrNZ++1eKafPdjzrqbjUiYLho9EbWYv0wDJSApWpm8h4/7d6DeMzrLfcwExKKDXEK7R0HmmvDxju3CxiVJ3Mcqt5wuI/jQcjIRnzGTO8rcCWjg0SvNmUJswdOf0p88AfH7wZdYsd4/XZgT7Ju7+eXzcVY5A2x4="

